name: IPTV Checker & Updater

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every 24 hours
  workflow_dispatch:

jobs:
  process-playlist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        playlist:
          - { url: "https://iptv-org.github.io/iptv/countries/id-jt.m3u", name: "uk" }
          - { url: "https://iptv-org.github.io/iptv/countries/id-jt.m3u", name: "us" }
          - { url: "https://iptv-org.github.io/iptv/countries/id-jt.m3u", name: "pk" }
          - { url: "https://iptv-org.github.io/iptv/countries/id-jt.m3u", name: "in" }
          - { url: "https://iptv-org.github.io/iptv/countries/id-jt.m3u", name: "ae" }
          - { url: "https://iptv-org.github.io/iptv/countries/id-jt.m3u", name: "sa" }
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Playlist
        run: |
          echo "Fetching ${{ matrix.playlist.url }}"
          curl -fsSL "${{ matrix.playlist.url }}" | sed '/^#EXTM3U/d' > playlist.m3u
          echo "Fetched playlist:"
          cat playlist.m3u

      - name: Ensure Playlist Header
        run: |
          if ! grep -q "^#EXTM3U" playlist.m3u; then
            sed -i '1i#EXTM3U' playlist.m3u
          fi
          echo "Ensured #EXTM3U header:"
          cat playlist.m3u

      - name: Append Additional Links to PK Playlist
        if: matrix.playlist.name == 'pk'
        run: |
          echo "No additional links to append for PK playlist."

      - name: Install Dependencies and iptv-checker via npm
        run: |
          sudo apt update
          sudo apt install -y nodejs npm curl jq ffmpeg
          npm install -g iptv-checker
          export PATH=$PATH:$(npm bin -g)

      - name: Validate Playlist Format
        run: |
          if ! grep -q "^#EXTINF" playlist.m3u; then
            echo "Invalid playlist format: Missing #EXTINF lines"
            exit 1
          fi
          if ! grep -q "^http" playlist.m3u; then
            echo "Invalid playlist format: Missing HTTP links"
            exit 1
          fi

      - name: Create Output Directory
        run: mkdir -p output

      - name: Run iptv-checker on the Playlist
        run: |
          iptv-checker playlist.m3u -o output
          echo "Online Playlist:"
          cat output/online.m3u

      - name: Upload Online Playlist
        uses: actions/upload-artifact@v4
        with:
          name: online_playlist_${{ matrix.playlist.name }}
          path: output/online.m3u

  merge-playlists:
    runs-on: ubuntu-latest
    needs: process-playlist
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Online Playlists
        uses: actions/download-artifact@v4
        with:
          path: online_playlists

      - name: Merge Online Playlists
        run: |
          echo "#EXTM3U" > final_online_playlist.m3u
          for file in online_playlists/*; do
            if [ -f "$file" ]; then
              sed '/^#EXTM3U/d' "$file" >> final_online_playlist.m3u
            fi
          done
          cat <<EOL >> final_online_playlist.m3u
          #EXTINF:-1,Saudi Quran
          http://webtv.dodear.asia:88/saudiquransd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Saudi Sunnah
          http://webtv.dodear.asia:88/saudisunnahsd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Ary QTV
          http://webtv.dodear.asia:88/aryqtvsd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Madni TV
          http://webtv.dodear.asia:88/madnitvsd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Animal Planet
          http://webtv.dodear.asia:88/skyanimalplanetddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1,National Geographic
          http://webtv.dodear.asia:88/skynatgeo/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Action Movies
          http://webtv.dodear.asia:88/osnmovieaction/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Sky Cinema
          http://webtv.dodear.asia:88/skycinemapremier/tracks-v1a1/mono.m3u8
          #EXTINF:-1,OSN movies
          http://webtv.dodear.asia:88/osnmovies/tracks-v1a1/mono.m3u8
          #EXTINF:-1,OSN Series
          http://webtv.dodear.asia:88/osnseries/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Sky Cinema Sci-fi
          http://webtv.dodear.asia:88/skycinemascifi/tracks-v1a1/mono.m3u8
          #EXTINF:-1,8xm
          http://webtv.dodear.asia:88/8xmsd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Jalwa Music
          http://webtv.dodear.asia:88/jalwamusicsd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,A Plus
          http://webtv.dodear.asia:88/aplushd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Aan TV
          http://webtv.dodear.asia:88/aantvhd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,A TV
          http://webtv.dodear.asia:88/atvhd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Aur Life
          http://webtv.dodear.asia:88/aurlifehdddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Aaj TV
          http://webtv.dodear.asia:88/aajtvsd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Apna TV
          http://webtv.dodear.asia:88/apnatv/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Ary Digital
          http://webtv.dodear.asia:88/arydigitalhd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Geo TV
          http://webtv.dodear.asia:88/geotvhdddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Hum TV
          http://webtv.dodear.asia:88/humtvsdddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1,24 News
          http://webtv.dodear.asia:88/24newshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,7 News
          http://webtv.dodear.asia:88/7newshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,92 News
          http://webtv.dodear.asia:88/92newshdddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Abn News
          http://webtv.dodear.asia:88/abnnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Aaj News
          http://webtv.dodear.asia:88/aajnewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Abbtak News
          http://webtv.dodear.asia:88/abbtaknewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Ary News
          http://webtv.dodear.asia:88/arynewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Bol News
          http://webtv.dodear.asia:88/bolnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Channel Five
          http://webtv.dodear.asia:88/channelfive/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Dawn News
          http://webtv.dodear.asia:88/dawnnewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Dunya News
          http://webtv.dodear.asia:88/dunyanewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Express News
          http://webtv.dodear.asia:88/expressnewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Geo News
          http://webtv.dodear.asia:88/geonewshdddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Hum News
          http://webtv.dodear.asia:88/humnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Ktn News
          http://webtv.dodear.asia:88/ktnnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Khyber News
          http://webtv.dodear.asia:88/khybernewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Lahore news
          http://webtv.dodear.asia:88/lahorenewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Neo News
          http://webtv.dodear.asia:88/neonewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Pnn News
          http://webtv.dodear.asia:88/pnnnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Sindh News
          http://webtv.dodear.asia:88/sindhnewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Talon News
          http://webtv.dodear.asia:88/talonnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Vsh News
          http://webtv.dodear.asia:88/vshnewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Ptv News
          http://webtv.dodear.asia:88/ptvnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Play TV
          http://webtv.dodear.asia:88/playtvsd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Public News
          http://webtv.dodear.asia:88/publicnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Such News
          http://webtv.dodear.asia:88/suchnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Samaa News
          http://webtv.dodear.asia:88/samaanewssdddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Suno News
          http://webtv.dodear.asia:88/sunonewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,A Sports
          http://webtv.dodear.asia:88/asportssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Astro Cric
          http://webtv.dodear.asia:88/astrocrichd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Ptv Sports
          http://webtv.dodear.asia:88/ptvsportssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Super Sports EPL
          http://webtv.dodear.asia:88/supersportseplhd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Starz Play Cric
          http://webtv.dodear.asia:88/starzplaycric/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Sky Sports Cric
          http://webtv.dodear.asia:88/skysportscrichd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Sky Sports EPL
          http://webtv.dodear.asia:88/skysportseplhd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Sky Main Event
          http://webtv.dodear.asia:88/skyspmainevent/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Willow Cricket Xtra
          http://webtv.dodear.asia:88/willowcricketxtra/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Ten Sports
          http://webtv.dodear.asia:88/tensportssdddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Willow Cric
          http://webtv.dodear.asia:88/willowcrichd/tracks-v1a1/mono.m3u8
          #EXTINF:-1,Sky Sports WWE
          http://webtv.dodear.asia:88/skysportswwe/tracks-v1a1/mono.m3u8
          EOL
          echo "Final Merged Online Playlist:"
          cat final_online_playlist.m3u

      - name: Commit & Push Final Merged Online Playlist to Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add final_online_playlist.m3u
          git commit -m "Update final online IPTV playlist $(date)" || echo "No changes to commit"
          git push

      - name: Update Gist with Final Merged Online Playlist (Optional)
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          if [ -z "${GIST_ID}" ] || [ -z "${GIST_TOKEN}" ]; then
            echo "Skipping Gist update: GIST_ID or GIST_TOKEN is not set."
          else
            echo "Updating Gist..."
            curl -X PATCH "https://api.github.com/gists/${GIST_ID}" \
              -H "Authorization: token ${GIST_TOKEN}" \
              -H "Content-Type: application/json" \
              -d "{\"files\": {\"final_online_playlist.m3u\": {\"content\": \"$(cat final_online_playlist.m3u | sed 's/\"/\\\"/g')\"}}}"
          fi
