name: IPTV Checker & Updater

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every 24 hours
  workflow_dispatch:

jobs:
  process-playlist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        playlist:
          - { url: "https://iptv-org.github.io/iptv/countries/pk.m3u", name: "pk" }
          - { url: "https://iptv-org.github.io/iptv/countries/in.m3u", name: "in" }
          - { url: "https://iptv-org.github.io/iptv/countries/uk.m3u", name: "uk" }
          - { url: "https://iptv-org.github.io/iptv/countries/us.m3u", name: "us" }
          - { url: "https://iptv-org.github.io/iptv/countries/ae.m3u", name: "ae" }
          - { url: "https://iptv-org.github.io/iptv/countries/sa.m3u", name: "sa" }
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Playlist
        run: |
          echo "Fetching ${{ matrix.playlist.url }}"
          curl -fsSL "${{ matrix.playlist.url }}" | sed '/^#EXTM3U/d' > playlist.m3u
          echo "Fetched playlist:"
          cat playlist.m3u

      - name: Update Group Title in Playlist
        run: |
          case "${{ matrix.playlist.name }}" in
            pk) group="Pakistan" ;;
            in) group="India" ;;
            uk) group="UK" ;;
            us) group="US" ;;
            ae) group="UAE" ;;
            sa) group="Saudi" ;;
            *) group="Unknown" ;;
          esac
          sed -i "s/group-title=\"[^\"]*\"/group-title=\"$group\"/g" playlist.m3u
          echo "Updated playlist with group-title=\"$group\":"
          cat playlist.m3u

      - name: Ensure Playlist Header
        run: |
          if ! grep -q "^#EXTM3U" playlist.m3u; then
            sed -i '1i#EXTM3U' playlist.m3u
          fi
          echo "Ensured #EXTM3U header:"
          cat playlist.m3u

      - name: Install Dependencies and iptv-checker via npm
        run: |
          sudo apt update
          sudo apt install -y nodejs npm curl jq ffmpeg
          npm install -g iptv-checker
          export PATH=$PATH:$(npm bin -g)

      - name: Check if Playlist is Empty
        run: |
          if [ ! -s playlist.m3u ]; then
            echo "Playlist is empty."
            exit 0
          fi

      - name: Validate Playlist Format
        run: |
          if ! grep -q "^#EXTINF" playlist.m3u; then
            echo "Invalid playlist format: Missing #EXTINF lines"
            exit 1
          fi
          if ! grep -q "^http" playlist.m3u; then
            echo "Invalid playlist format: Missing HTTP links"
            exit 1
          fi

      - name: Create Output Directory
        run: mkdir -p output

      - name: Run iptv-checker on the Playlist
        run: |
          iptv-checker playlist.m3u -o output
          echo "Online Playlist:"
          cat output/online.m3u

      - name: Upload Online Playlist
        uses: actions/upload-artifact@v4
        with:
          name: online_playlist_${{ matrix.playlist.name }}
          path: output/online.m3u

  merge-playlists:
    runs-on: ubuntu-latest
    needs: process-playlist
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Online Playlists
        uses: actions/download-artifact@v4
        with:
          path: online_playlists

      - name: Merge Online Playlists
        run: |
          echo "#EXTM3U" > final_online_playlist.m3u
          for file in $(find online_playlists -type f); do
            echo "Merging $file"
            sed '/^#EXTM3U/d' "$file" >> final_online_playlist.m3u
          done
          cat <<EOL >> final_online_playlist.m3u
          #EXTINF:-1, group-title="Pakistan", Saudi Quran
          http://webtv.dodear.asia:88/saudiquransd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Saudi Sunnah
          http://webtv.dodear.asia:88/saudisunnahsd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Ary QTV
          http://webtv.dodear.asia:88/aryqtvsd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Madni TV
          http://webtv.dodear.asia:88/madnitvsd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Animal Planet
          http://webtv.dodear.asia:88/skyanimalplanetddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", National Geographic
          http://webtv.dodear.asia:88/skynatgeo/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Action Movies
          http://webtv.dodear.asia:88/osnmovieaction/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Sky Cinema
          http://webtv.dodear.asia:88/skycinemapremier/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", OSN movies
          http://webtv.dodear.asia:88/osnmovies/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", OSN Series
          http://webtv.dodear.asia:88/osnseries/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Sky Cinema Sci-fi
          http://webtv.dodear.asia:88/skycinemascifi/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", 8xm
          http://webtv.dodear.asia:88/8xmsd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Jalwa Music
          http://webtv.dodear.asia:88/jalwamusicsd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", A Plus
          http://webtv.dodear.asia:88/aplushd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Aan TV
          http://webtv.dodear.asia:88/aantvhd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", A TV
          http://webtv.dodear.asia:88/atvhd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Aur Life
          http://webtv.dodear.asia:88/aurlifehdddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Aaj TV
          http://webtv.dodear.asia:88/aajtvsd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Apna TV
          http://webtv.dodear.asia:88/apnatv/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Ary Digital
          http://webtv.dodear.asia:88/arydigitalhd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Geo TV
          http://webtv.dodear.asia:88/geotvhdddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Hum TV
          http://webtv.dodear.asia:88/humtvsdddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", 24 News
          http://webtv.dodear.asia:88/24newshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", 7 News
          http://webtv.dodear.asia:88/7newshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", 92 News
          http://webtv.dodear.asia:88/92newshdddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Abn News
          http://webtv.dodear.asia:88/abnnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Aaj News
          http://webtv.dodear.asia:88/aajnewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Abbtak News
          http://webtv.dodear.asia:88/abbtaknewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Ary News
          http://webtv.dodear.asia:88/arynewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Bol News
          http://webtv.dodear.asia:88/bolnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Channel Five
          http://webtv.dodear.asia:88/channelfive/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Dawn News
          http://webtv.dodear.asia:88/dawnnewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Dunya News
          http://webtv.dodear.asia:88/dunyanewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Express News
          http://webtv.dodear.asia:88/expressnewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Geo News
          http://webtv.dodear.asia:88/geonewshdddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Hum News
          http://webtv.dodear.asia:88/humnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Ktn News
          http://webtv.dodear.asia:88/ktnnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Khyber News
          http://webtv.dodear.asia:88/khybernewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Lahore news
          http://webtv.dodear.asia:88/lahorenewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Neo News
          http://webtv.dodear.asia:88/neonewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Pnn News
          http://webtv.dodear.asia:88/pnnnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Sindh News
          http://webtv.dodear.asia:88/sindhnewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Talon News
          http://webtv.dodear.asia:88/talonnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Vsh News
          http://webtv.dodear.asia:88/vshnewssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Ptv News
          http://webtv.dodear.asia:88/ptvnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Play TV
          http://webtv.dodear.asia:88/playtvsd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Public News
          http://webtv.dodear.asia:88/publicnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Such News
          http://webtv.dodear.asia:88/suchnewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Samaa News
          http://webtv.dodear.asia:88/samaanewssdddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Suno News
          http://webtv.dodear.asia:88/sunonewshd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", A Sports
          http://webtv.dodear.asia:88/asportssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Astro Cric
          http://webtv.dodear.asia:88/astrocrichd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Ptv Sports
          http://webtv.dodear.asia:88/ptvsportssd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Super Sports EPL
          http://webtv.dodear.asia:88/supersportseplhd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Starz Play Cric
          http://webtv.dodear.asia:88/starzplaycric/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Sky Sports Cric
          http://webtv.dodear.asia:88/skysportscrichd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Sky Sports EPL
          http://webtv.dodear.asia:88/skysportseplhd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Sky Main Event
          http://webtv.dodear.asia:88/skyspmainevent/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Willow Cricket Xtra
          http://webtv.dodear.asia:88/willowcricketxtra/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Ten Sports
          http://webtv.dodear.asia:88/tensportssdddr/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Willow Cric
          http://webtv.dodear.asia:88/willowcrichd/tracks-v1a1/mono.m3u8
          #EXTINF:-1, group-title="Pakistan", Sky Sports WWE
          http://webtv.dodear.asia:88/skysportswwe/tracks-v1a1/mono.m3u8
          EOL
          echo "Final Merged Online Playlist:"
          cat final_online_playlist.m3u

      - name: Commit & Push Final Merged Online Playlist to Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add final_online_playlist.m3u
          git commit -m "Update final online IPTV playlist $(date)" || echo "No changes to commit"
          git push
    
          fi
