name: IPTV Checker & Updater

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  process-playlist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        playlist:
          - { url: "https://iptv-org.github.io/iptv/countries/uk.m3u", name: "uk" }
          - { url: "https://iptv-org.github.io/iptv/countries/us.m3u", name: "us" }
          - { url: "https://iptv-org.github.io/iptv/countries/pk.m3u", name: "pk" }
          - { url: "https://iptv-org.github.io/iptv/countries/in.m3u", name: "in" }
          - { url: "https://iptv-org.github.io/iptv/countries/ae.m3u", name: "ae" }
          - { url: "https://iptv-org.github.io/iptv/countries/sa.m3u", name: "sa" }
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Playlist
        run: |
          echo "Fetching ${{ matrix.playlist.url }}"
          curl -fsSL "${{ matrix.playlist.url }}" | sed '/^#EXTM3U/d' > playlist.m3u
          echo "Fetched playlist:"
          cat playlist.m3u

      - name: Ensure Playlist Header
        run: |
          if ! grep -q "^#EXTM3U" playlist.m3u; then
            sed -i '1i#EXTM3U' playlist.m3u
          fi
          echo "Ensured #EXTM3U header:"
          cat playlist.m3u

      - name: Install Dependencies and iptv-checker via npm
        run: |
          sudo apt update
          sudo apt install -y nodejs npm curl jq ffmpeg
          npm install -g iptv-checker
          export PATH=$PATH:$(npm bin -g)

      - name: Validate Playlist Format
        run: |
          if ! grep -q "^#EXTINF" playlist.m3u; then
            echo "Invalid playlist format: Missing #EXTINF lines"
            exit 1
          fi
          if ! grep -q "^http" playlist.m3u; then
            echo "Invalid playlist format: Missing HTTP links"
            exit 1
          fi

      - name: Create Output Directory
        run: mkdir -p output

      - name: Run iptv-checker on the Playlist
        run: |
          iptv-checker playlist.m3u -o output
          echo "Online Playlist:"
          cat output/online.m3u

      - name: Upload Online Playlist
        uses: actions/upload-artifact@v4
        with:
          name: online_playlist_${{ matrix.playlist.name }}
          path: output/online.m3u

  merge-playlists:
    runs-on: ubuntu-latest
    needs: process-playlist
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Online Playlists
        uses: actions/download-artifact@v4
        with:
          path: online_playlists

      - name: Merge Online Playlists
        run: |
          echo "#EXTM3U" > final_online_playlist.m3u
          for file in online_playlists/*; do
            sed '/^#EXTM3U/d' "$file" >> final_online_playlist.m3u
          done
          echo "Final Merged Online Playlist:"
          cat final_online_playlist.m3u

      - name: Commit & Push Final Merged Online Playlist to Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add final_online_playlist.m3u
          git commit -m "Update final online IPTV playlist $(date)" || echo "No changes to commit"
          git push

      - name: Update Gist with Final Merged Online Playlist (Optional)
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          if [ -z "${GIST_ID}" ] || [ -z "${GIST_TOKEN}"]; then
            echo "Skipping Gist update: GIST_ID or GIST_TOKEN is not set."
          else
            echo "Updating Gist..."
            curl -X PATCH "https://api.github.com/gists/${GIST_ID}" \
              -H "Authorization: token ${GIST_TOKEN}" \
              -H "Content-Type: application/json" \
              -d "{\"files\": {\"final_online_playlist.m3u\": {\"content\": \"$(cat final_online_playlist.m3u | sed 's/\"/\\\"/g')\"}}}"
          fi
